# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KawsWebEnter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUrlForTest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('webname', models.CharField(blank=True, max_length=40, null=True)),
                ('weburl', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='testuser',
            name='adress',
        ),
    ]
