# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KawsWebEnter', '0003_testplanversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlatformIntroduce',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('platformname', models.CharField(blank=True, max_length=50)),
                ('platformintroduce', models.CharField(blank=True, max_length=255, null=True)),
                ('Urllink', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
