# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KawsWebEnter', '0005_testcaseversiondisplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoblieStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returntime', models.DateField(auto_created=True, auto_now_add=True)),
                ('lendtime', models.DateField(auto_created=True, auto_now_add=True)),
                ('mobliename', models.CharField(max_length=255)),
                ('mobilestatus', models.IntegerField(default=1)),
                ('systemversion', models.CharField(max_length=255)),
                ('user', models.ManyToManyField(to='KawsWebEnter.Testuser')),
            ],
        ),
        migrations.CreateModel(
            name='TbUser',
            fields=[
                ('userkey', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('mobile', models.CharField(blank=True, max_length=66, null=True)),
                ('username', models.CharField(max_length=64)),
                ('imageurl', models.CharField(blank=True, max_length=256, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('type', models.CharField(blank=True, max_length=1, null=True)),
                ('sickkindsid', models.CharField(blank=True, max_length=32, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('sickdate', models.DateField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=32, null=True)),
                ('departments', models.CharField(blank=True, max_length=32, null=True)),
                ('hospital', models.CharField(blank=True, max_length=50, null=True)),
                ('sickdegree', models.CharField(blank=True, max_length=16, null=True)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('orgtype', models.CharField(blank=True, max_length=1, null=True)),
                ('userid', models.CharField(blank=True, max_length=32, null=True)),
                ('quenotice', models.IntegerField(blank=True, null=True)),
                ('commentnotice', models.CharField(blank=True, max_length=1, null=True)),
                ('attennotice', models.CharField(blank=True, max_length=1, null=True)),
                ('clienttype', models.CharField(blank=True, max_length=1, null=True)),
                ('channelid', models.CharField(blank=True, max_length=32, null=True)),
                ('relationship', models.CharField(blank=True, max_length=32, null=True)),
                ('registwhy', models.CharField(blank=True, max_length=32, null=True)),
                ('usestatus', models.IntegerField(blank=True, null=True)),
                ('medicalrecord', models.CharField(blank=True, max_length=1, null=True)),
                ('keywords', models.IntegerField(blank=True, null=True)),
                ('doctordegree', models.CharField(blank=True, max_length=1, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('praisenum', models.CharField(blank=True, db_column='praiseNUM', max_length=100, null=True)),
                ('joinactive', models.CharField(blank=True, max_length=1, null=True)),
                ('invitationcode', models.CharField(blank=True, max_length=30, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('sectype', models.CharField(blank=True, max_length=2, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('commentnum', models.CharField(blank=True, db_column='commentNUM', max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=20, null=True)),
                ('has_set_diseased_state', models.IntegerField(blank=True, null=True)),
                ('latest_checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('has_mood_note_notice', models.IntegerField(blank=True, null=True)),
                ('has_community_notice', models.IntegerField(blank=True, null=True)),
                ('has_doctor_comment_notice', models.IntegerField(blank=True, null=True)),
                ('has_apply_doctor_notice', models.IntegerField(blank=True, null=True)),
                ('has_message_notice', models.IntegerField(blank=True, null=True)),
                ('has_followed_notice', models.IntegerField(blank=True, null=True)),
                ('modified_username_at', models.DateTimeField(blank=True, null=True)),
                ('old_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sign', models.CharField(blank=True, max_length=255, null=True)),
                ('money', models.CharField(blank=True, max_length=255, null=True)),
                ('doctorvideo', models.CharField(blank=True, max_length=255, null=True)),
                ('wx_open_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
    ]
