# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KawsWebEnter', '0006_mobliestatus_tbuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobliestatus',
            name='mobilestatus',
        ),
    ]
