# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KawsWebEnter', '0007_remove_mobliestatus_mobilestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobliestatus',
            name='mobilestatus',
            field=models.IntegerField(default=1),
        ),
    ]
